name: Build Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Cargo Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the repo
        uses: actions/checkout@v3

      - name: Build project
        run: cargo build