name: Publish and Deploy

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: shreyaskuloor/abc_chatter_bot
      
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy_to_cloud_run:
    name: Deploy Bot to Cloud Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the repo
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with: 
          workload_identity_provider: projects/354053214684/locations/global/workloadIdentityPools/github-actions-pool/providers/github
          service_account: github-actions-pipeline@tokyo-dream-387801.iam.gserviceaccount.com
      
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: abc-chatter-bot
          image: us-docker.pkg.dev/shreyaskuloor/abc_chatter_bot/abc_chatter_bot:latest
          region: us-central1
          flags: '--min-instances=1 --no-cpu-throttling'
          env_vars: |
            DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}
            THREAD_MESSAGE_LIMIT=${{ vars.THREAD_MESSAGE_LIMIT }}
            OPENAI_BASE_URL=${{ vars.OPENAI_BASE_URL }}
            OPENAI_MODEL=${{ vars.OPENAI_MODEL }}
            OPENAI_SYSTEM_CONTENT=${{ vars.OPENAI_SYSTEM_CONTENT }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            RANDOM_REACT_UPPER_BOUND=${{ vars.RANDOM_REACT_UPPER_BOUND }}
            CHUG_EMOTE_NAME=${{ vars.CHUG_EMOTE_NAME }}
            DEFAULT_GAME_IMAGE=${{ vars.DEFAULT_GAME_IMAGE }}
            IGDB_BASE_URL=${{ vars.IGDB_BASE_URL }}
            IGDB_AUTH_URL=${{ vars.IGDB_AUTH_URL }}
            IGDB_CLIENT_ID=${{ secrets.IGDB_CLIENT_ID }}
            IGDB_CLIENT_SECRET=${{ secrets.IGDB_CLIENT_SECRET }}
            CHUG_TIMEOUT_SECONDS=${{ vars.CHUG_TIMEOUT_SECONDS }}
            GAME_IMAGE_BASE_URL=${{ vars.GAME_IMAGE_BASE_URL }}
            GAME_IMAGE_SIZE=${{ vars.GAME_IMAGE_SIZE }}
            BOT_COMMAND_PREFIX=${{ vars.BOT_COMMAND_PREFIX }}
            CHUG_POLL_IMAGE=${{ vars.CHUG_POLL_IMAGE }}
            STABLE_DIFFUSION_BASE_URL=${{ secrets.STABLE_DIFFUSION_BASE_URL }}
            STABLE_DIFFUSION_SAMPLING_STEPS=${{ vars.STABLE_DIFFUSION_SAMPLING_STEPS }}
            ELEVEN_LABS_API_KEY=${{ secrets.ELEVEN_LABS_API_KEY }}
            ELEVEN_LABS_BASE_URL=${{ vars.ELEVEN_LABS_BASE_URL }}
            ELEVEN_LABS_STABILITY=${{ vars.ELEVEN_LABS_STABILITY }}
            ELEVEN_LABS_SIMILARITY_BOOST=${{ vars.ELEVEN_LABS_SIMILARITY_BOOST }}